### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by lyricnight** [lyricnight/infinity#1]
Make blocker persistent actually work - (DONE)
Add thread changer and unfocused cpu to internals - (DONE)
Fix bug where string type settings did not save to file correctly - (DONE)
investigate broken shaderchams - (DONE)
fix the friendsystem - (DONE)
add doubles to autocity - done for hf
make friendsystem not require a restart to save - (DONE)
add bpt to hf - (DONE)
add info logger to client for eventbus and initialisation debugging - (DONE)
migrate blocker and anticev onto new switch thing - done
fix getDisplayInfo null return for some classes - done
rewrite entire block placing and attacking methods - done for placing
fix animations - done
add coords back to hud - done
add potions - done
add some sort of arrowswapper - done
have another look at the client's rotation and blockplace systems - need to add strict rotations - switch done
fix packetdelay
fix configs
maybe rewrite the whole block place stuff 

BIG - HUD Rewrite with Alphastep - done

**Comment by boy-kisser** [comment]
shut up niggaLmaoWtf

**Comment by lyricnight** [comment]
i own more fonts than you
